image: busybox

pages:
    stage: deploy
    script:
        - mkdir .public
        - cp -r -- * .public
        - rm .public/README.md
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - main
